name: 🧪 Run Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    strategy:
        matrix:
            os: [ubuntu-latest]
    name: 🧪 Run Publish Dry-run 
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Cache Publish
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run Check
      run: cargo publish --dry-run --verbose